### ISSUE TITLE
Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by TheAifam5** [christophschlosser/doxdocgen#79]
Log:
```
Cannot read property 'text' of undefined: TypeError: Cannot read property 'text' of undefined
    at CodeParserController.check (C:\Users\MateuszPaluszkiewicz\.vscode\extensions\cschlosser.doxdocgen-0.3.1\out\CodeParserController.js:44:42)
    at CodeParserController.onEvent (C:\Users\MateuszPaluszkiewicz\.vscode\extensions\cschlosser.doxdocgen-0.3.1\out\CodeParserController.js:85:19)
    at CodeParserController.vscode_1.workspace.onDidChangeTextDocument (C:\Users\MateuszPaluszkiewicz\.vscode\extensions\cschlosser.doxdocgen-0.3.1\out\CodeParserController.js:26:22)
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:784)
    at e.$acceptDirtyStateChanged (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:685:973)
    at e.$acceptModelSaved (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:685:723)
    at e._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:832)
    at e._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:636:550)
    at e._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:631)
    at e._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:635:400)
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:634:315
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:637:395
    at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:95:432
    at e.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:96:764)
    at Socket.<anonymous> (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\node\extensionHostProcess.js:154:338)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at Pipe.onread (net.js:560:20)
```

**Comment by christophschlosser** [comment]
I need more information.

VSCode version, when did this happen, what were you trying to do?

**Comment by TheAifam5** [comment]
Happens while editing any file format.
Version: 
Version 1.24.1
Commit 24f62626b222e9a8313213fb64b10d741a326288
Date 2018-06-13T17:51:32.889Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by christophschlosser** [comment]
This is super strange and I can not reproduce it. This can only occur when the extension receives an event from the VS Code runtime and the event becomes undefined while we're reading a property from it.

Another thing is that JSON should not trigger the extension at all!

I added another check if the event exists. I will release it today hope this fixes it. Once you updated to 0.3.2 it would be great to hear back from you.

**Comment by TheAifam5** [comment]
@christophschlosser looks like that's a breaking change inside the VSCode. I noticed the same bug in other package.
